server:
  port: 1579

spring:
  ai:
    ollama:
      base-url: http://100.101.147.112:11434

# Redis
redis:
  sdk:
    config:
      host: 100.101.147.112
      port: 16379
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true

logging:
  level:
    root: info
  config: classpath:logback-spring.xml
